Website/MtG_UCC/MtG_UCC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MtG_UCC.Data;
using MtG_UCC.Models.Database;
using System.Diagnostics;
using static MtG_UCC.Services.GlobalMethods;

namespace MtG_UCC.Controllers {
    public class AdminController : Controller {
        private readonly UserManager<IdentityUser> users;
        private readonly RoleManager<IdentityRole> roles;
        public AdminController(UserManager<IdentityUser> _users, RoleManager<IdentityRole> _roles) {
            users = _users;
            roles = _roles;
        }

        [Authorize(Roles = "Administrator,Owner")]
        public async Task<IActionResult> UserManagement() {
            List<UsersWithRoles> usersWithRoles = new();

            usersWithRoles = await GetAllUsersAndRoles(users, User);

            ViewData["RolesList"] = await roles.Roles.ToListAsync();

            return View(usersWithRoles);
        }

        [HttpPost, Authorize(Roles = "Administrator,Owner")]
        public async Task<IActionResult> EditRole(string UserId, string RoleId) {
            Debug.WriteLine($"ROLE ID ::: {RoleId}"); Console.WriteLine($"ROLE ID ::: {RoleId}");
            if (await UpdateUserRole(users, User, UserId, RoleId)) {
                return RedirectToAction("UserManagement");
            } else {
                return BadRequest($"{UserId} {RoleId}");
            }
        }

        [Authorize(Roles = "Administrator,Owner")]
        public async Task<IActionResult> UserStatistics() { 
            List<CardStat> top25 = await RetrieveTop25(users, User);

            return View(top25);
        }

        //public async Task<IActionResult> DeleteUser(string UserId) { 
        
        //}

    }
}

Website/MtG_UCC/MtG_UCC/Controllers/ScryfallController.cs
using Microsoft.AspNetCore.Mvc;
using MtG_UCC.Models.Scryfall_Card;
using MtG_UCC.Models.Scryfall_Search;
using static MtG_UCC.Services.GlobalMethods;

namespace MtG_UCC.Controllers {
    public class ScryfallController : Controller {

        public IActionResult Search() {
            List<Card> cards = new();

            SearchParameters parameters = new();

            ViewData["Parameters"] = parameters;

            return View(cards);
        }

        [HttpPost]
        public async Task<IActionResult> Search(SearchParameters parameters) {
            List<Card> cards = new();

            cards = await RetrieveCardsFromSearch(parameters);

            ViewData["Parameters"] = parameters;

            return View(cards);
        }
    }
}

Website/MtG_UCC/MtG_UCC/Views/Shared/_CardGrid.cshtml
@model List<Collection>

@{
    int count = 0;
}

<div class="grid-container m-3">
    @if (Model != null && Model.Count > 0) {
        var previousCardName = "";
        var isFirstCardName = true;
        var currentIndex = 0;

        while (currentIndex < Model.Count) {
            var currentCardName = Model[currentIndex].CardName;

            if (currentCardName != previousCardName) {
                if (!isFirstCardName) {
                    <hr />
                } else {
                    isFirstCardName = false;
                }

                <h4 class="Plains_pFG ms-4 my-1">@Model[currentIndex].CardName</h4>
                previousCardName = currentCardName;
            }

            <div class="row mx-1">
                @for (int col = 0; col < 3; col++) {
                    if(col == 0) {
                        count = 0;
                    }

                    if (currentIndex < Model.Count && Model[currentIndex].CardName == currentCardName) {
                        var item = Model[currentIndex];
                        await Html.RenderPartialAsync("_CollectionItem", item);
                        currentIndex++;
                    } else {
                        <div class="container col-4"></div>
                    }

                    ++count;
                }

                @if ((currentIndex + 1)! > Model.Count) {
                    if (count != 3) {
                        for (int i = 0; i < (3 - count); ++i) {
                            <div class="container col-4"></div>
                        }
                    }
                }
            </div>
        }
    }
</div>

Website/MtG_UCC/MtG_UCC/Views/Shared/_CollectionItem.cshtml
@using MtG_UCC.Models.Scryfall_Search;
@using Newtonsoft.Json;
@model Collection

@{
    var uuid = Guid.NewGuid();
}

<div class="container p-grid col-4">
    <div class="card h-100 m-0 p-card">
        <div class="row h-100">
            <div class="col-card h-100 p-0 m-0 tooltips" data-placement="top" title="View Card Details">
                <img class="CardImage" id="@("cardContainer_" + uuid)" />
            </div>

            <div class="margin-collection Plains_FG rounded-3 tooltips" data-placement="top" title="Edit Collection Entry">
                <div class="d-flex flex-column justify-content-around card-body p-0 m-1" style="height: 100%">
                    @*<a class="text-dark text-decoration-none" asp-controller="Controller" asp-action="Edit" asp-route-Collection="@Model">*@
                        <div class="card-text">
                            <h6 class="text-decoration-underline m-0">Set:</h6>
                            <div class="d-flex flex-row align-items-center">
                                <div class="m-0 align-self-center">
                                    <iframe class="IconImage" id="@("iconContainer_" + uuid)"></iframe>
                                </div>
                                <span class="m-0 align-self-start">@Model.SetName</span>
                            </div>
                        </div>
                        <div class="card-text">
                            <h6 class="text-decoration-underline m-0">Storage Location:</h6>
                            <p class="m-0">@Model.StorageLocation</p>
                        </div>
                        <div class="card-text">
                            <div class="d-flex flex-row justify-content-between">
                                <h6 class="m-0 align-self-start text-decoration-underline">Condition:</h6>
                                <h6 class="m-0 align-self-end text-decoration-underline">Quantity:</h6>
                            </div>
                            <div class="d-flex flex-row justify-content-between">
                                <p class="m-0 align-self-center">@Model.CardCondition.Name</p>
                                <p class="m-0 align-self-center">@Model.Quantity</p>
                            </div>

                            @*<div class="d-flex flex-row justify-content-between">
                                <p class="m-0 align-self-center">@Model.CardCondition.Name</p>
                                <div class="m-0 d-flex flex-row justify-content-between w-Quantity">
                                    <div class="m-0 align-self-center">
                                    <a href="#" class="text-danger text-decoration-none">
                                    <i class="bi bi-dash-circle-fill minus-icon"></i>
                                    </a>
                                    </div>
                                    <div class="m-0 align-self-center">
                                        <p class="m-0">@Model.Quantity</p>
                                    </div>
                                    <div class="m-0 align-self-center">
                                    <a href="#" class="text-primary text-decoration-none">
                                    <i class="bi bi-plus-circle-fill plus-icon"></i>
                                    </a>
                                    </div>
                                </div>
                            </div>*@

                        </div>
                    @*</a>*@
                    <div class="card-text">
                        <div class="d-flex flex-row justify-content-between">
                            <!-- Minus Button -->
                            @*<div class="m-0 align-self-center">
                                <a href="#" class="text-danger text-decoration-none">
                                    <i class="bi bi-dash-circle-fill minus-icon fs-3"></i>
                                </a>
                            </div>*@
                            @*<div class="m-0 align-self-center">
                                <a class="btn btn-sm btn-block btn-info rounded-pill px-5" asp-controller="Collection" asp-action="Edit" asp-route-Record="@Model">Edit</a>
                            </div>*@
                            <form class="d-none" id="editForm_@uuid" method="get" action="@Url.Action("Edit", "Collection")">
                                <input type="hidden" name="json" value="@JsonConvert.SerializeObject(Model)" />
                            </form>
                            @*<form class="d-none" id="deleteForm_@uuid" method="get" action="@Url.Action("Delete", "Collection")">
                                <input type="hidden" name="json" value="@JsonConvert.SerializeObject(Model)" />
                            </form>*@
                            <div class="m-0 row">
                                @*<div class="col-6">
                                    <button class="btn btn-sm btn-block btn-danger rounded-pill px-3 edit-button" form="deleteForm_@uuid">Delete</button>
                                </div>*@
                                <div class="col-6 px-4">
                                    <button class="btn btn-sm btn-block btn-warning rounded-pill text-center px-5 edit-button" form="editForm_@uuid">Edit</button>
                                </div>
                            </div>
                            <!-- Plus Button -->
                            @*<div class="m-0 align-self-center">
                                <a href="#" class="text-primary text-decoration-none">
                                    <i class="bi bi-plus-circle-fill plus-icon fs-3"></i>
                                </a>
                            </div>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>






<script>
    var imageUrl = "@Model.CardFace";
    var containerId = "@("cardContainer_" + uuid.ToString())";
    var img = document.getElementById(containerId);

    function displayCard(img) {
        fetch(imageUrl)
            .then(response => response.blob())
            .then(blob => {
                var reader = new FileReader();
                reader.onloadend = function () {
                    img.src = reader.result;
                };
                reader.readAsDataURL(blob);
            });
    }
    displayCard(img);
</script>

<script>
    var imageUrl = "@Model.SetIcon";
    var containerId = "@("iconContainer_" + uuid.ToString())";
    var iframe = document.getElementById(containerId);

    function displayIcon(iframe) {
        iframe.src = imageUrl;
    }
    displayIcon(iframe);
</script>

Website/MtG_UCC/MtG_UCC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magic: The Gathering - Unofficial Collector's Compendium</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MtG_UCC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light Plains_FG border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="container d-flex align-items-center flex-row">
                        <!-- Normal image -->
                        <img class="logo normal-image" src="@Url.Content("~/images/Icon/Colorless.png")" />

                        <!-- Hover image -->
                        <img class="logo hover-image" src="@Url.Content("~/images/Icon/ColoredMana.png")" style="display: none;" />

                        <span class="siteName">&nbsp; MtG: UCC</span>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.Identity.IsAuthenticated) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Collection" asp-action="Compendium">Compendium</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Collection" asp-action="Collection">Collection</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scryfall" asp-action="Search">Search</a>
                        </li>
                        @if(User.IsInRole("Administrator") || User.IsInRole("Owner")) {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administrative
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="UserManagement">User Management</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="UserStatistics">User Statistics</a>
                                </div>
                            </li>
                        }
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="mx-3 mt-3 mb-5 p-0">
        <main role="main" class="p-0 m-0">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted Plains_BG">
        <div class="container">
            &copy; 2023 - Magic: The Gathering - Unofficial Collector's Compendium @*- <a asp-area="" asp-controller="Home" asp-action="HelpDocumentation">Help Documentation</a>*@
        </div>
    </footer>
    @*<script src="https://unpkg.com/flatted/umd/index.min.js"></script>*@
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Website/MtG_UCC/MtG_UCC/Views/Shared/_SearchFull.cshtml
@using MtG_UCC.Models.Scryfall_Search

@model SearchParameters

<form asp-controller="Scryfall" asp-action="Search" method="post">
    <div class="container m-0 p-0 justify-content-center align-items-center border border-2 border-dark rounded-2 row CardBack">
        <div class="row">
            <div class="container my-2 col-6 border border-2 border-dark rounded-2 FormBack">
                <h4 class="text-center my-2 Handwritten">Search Modes</h4>
                <div class="row my-2 justify-content-center align-items-center">
                    <div class="col-auto me-2 d-flex align-items-center">
                        <div class="text-start">
                            @Html.LabelFor(m => m.Mode.Unique, new { @class = "pe-3" })
                            @Html.DropDownListFor(m => m.Mode.Unique, Html.GetEnumSelectList(typeof(RollupMode)), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Mode.Unique, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-auto me-2 d-flex align-items-center">
                        <div class="text-start">
                            @Html.LabelFor(m => m.Mode.Sort)
                            @Html.DropDownListFor(m => m.Mode.Sort, Html.GetEnumSelectList(typeof(SortBy)), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Mode.Sort, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-auto d-flex align-items-center">
                        <div class="text-start">
                            @Html.LabelFor(m => m.Mode.Order)
                            @Html.DropDownListFor(m => m.Mode.Order, Html.GetEnumSelectList(typeof(SortOrder)), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Mode.Order, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <h4 class="text-center my-2 Handwritten">Inclusions</h4>
                <div class="row my-2 justify-content-center align-items-center">
                    <div class="col-auto">
                        @Html.LabelFor(m => m.Inclusions.IncludeExtras, new { @class = "col-form-label" })
                        @Html.CheckBoxFor(m => m.Inclusions.IncludeExtras, new { @class = "form-check-input", @style = "width:2em; height:2em;" })
                        @Html.ValidationMessageFor(m => m.Inclusions.IncludeExtras, String.Empty, new { @class = "text-danger" })
                    </div>
                    <div class="col-auto">
                        @Html.LabelFor(m => m.Inclusions.IncludeMultilingual, new { @class = "col-form-label" })
                        @Html.CheckBoxFor(m => m.Inclusions.IncludeMultilingual, new { @class = "form-check-input", @style = "width:2em; height:2em;" })
                        @Html.ValidationMessageFor(m => m.Inclusions.IncludeMultilingual, String.Empty, new { @class = "text-danger" })
                    </div>
                    <div class="col-auto">
                        @Html.LabelFor(m => m.Inclusions.IncludeVariations, new { @class = "col-form-label" })
                        @Html.CheckBoxFor(m => m.Inclusions.IncludeVariations, new { @class = "form-check-input", @style = "width:2em; height:2em;" })
                        @Html.ValidationMessageFor(m => m.Inclusions.IncludeVariations, String.Empty, new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="container my-2 col-6 border border-2 border-dark rounded-2 FormBack">
                <h4 class="text-center my-2 Handwritten">Details</h4>
                <div class="row my-2 justify-content-center">
                    <div class="col-auto d-flex flex-wrap align-content-end">
                        @Html.LabelFor(m => m.ExactName, new { @class = "col-form-label me-1" })
                        @Html.CheckBoxFor(m => m.ExactName, new { @class = "form-check-input", @style = "width:2em; height:2em;" })
                        @Html.ValidationMessageFor(m => m.ExactName, String.Empty, new { @class = "text-danger" })
                    </div>
                    <div class="col-auto d-flex align-items-center">
                        <div class="text-start">
                            @Html.LabelFor(m => m.CardName)
                            @Html.TextBoxFor(m => m.CardName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.CardName, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-auto d-flex align-items-center">
                        <div class="text-start">
                            @Html.LabelFor(m => m.Set)
                            @Html.TextBoxFor(m => m.Set, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Set, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row my-2 justify-content-center">
                    <div class="col-auto d-flex flex-wrap align-content-end">
                        @Html.LabelFor(m => m.Banned, new { @class = "col-form-label me-1" })
                        @Html.CheckBoxFor(m => m.Banned, new { @class = "form-check-input", @style = "width:2em; height:2em;" })
                        @Html.ValidationMessageFor(m => m.Banned, String.Empty, new { @class = "text-danger" })
                    </div>
                    <div class="col-auto d-flex align-items-center">
                        <div class="text-start">
                            @Html.LabelFor(m => m.Legality)
                            @Html.DropDownListFor(m => m.Legality, Html.GetEnumSelectList(typeof(Legalities)), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Legality, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-auto d-flex align-items-center">
                        <div class="text-start">
                            @Html.LabelFor(m => m.Rarity)
                            @Html.DropDownListFor(m => m.Rarity, Html.GetEnumSelectList(typeof(Rarities)), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Rarity, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container mb-2 border border-2 border-dark rounded-2 FormBack">
                <div class="row justify-content-center my-2">
                    <div class="col-auto mx-5 mana-checkbox" onclick="toggleManaCheckbox(this)">
                        <span class="mana-icon check-swamp undecided"></span>
                        @Html.DropDownListFor(m => m.Colors.Black, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                    </div>
                    <div class="col-auto mx-5 mana-checkbox" onclick="toggleManaCheckbox(this)">
                        <span class="mana-icon check-forest undecided"></span>
                        @Html.DropDownListFor(m => m.Colors.Green, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                    </div>
                    <div class="col-auto mx-5 mana-checkbox" onclick="toggleManaCheckbox(this)">
                        <span class="mana-icon check-mountain undecided"></span>
                        @Html.DropDownListFor(m => m.Colors.Red, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                    </div>
                    <div class="col-auto mx-5 mana-checkbox" onclick="toggleManaCheckbox(this)">
                        <span class="mana-icon check-island undecided"></span>
                        @Html.DropDownListFor(m => m.Colors.Blue, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                    </div>
                    <div class="col-auto mx-5 mana-checkbox" onclick="toggleManaCheckbox(this)">
                        <span class="mana-icon check-plain undecided"></span>
                        @Html.DropDownListFor(m => m.Colors.White, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="d-flex flex-row justify-content-center mb-2">
                <button class="btn btn-block btn-Forest_BG w-50 px-5" type="submit">Search</button>
            </div>
        </div>
    </div>
</form>

Website/MtG_UCC/MtG_UCC/Views/Shared/_SearchGrid.cshtml
@using MtG_UCC.Models.Scryfall_Card;
@model List<Card>

@{
    int count = 0;
}

<div class="grid-container me-5 scroll-view">
    @if (Model != null && Model.Count > 0) {
        var currentIndex = 0;

        while (currentIndex < Model.Count) {

            <div class="row m-2">
                @for (int col = 0; col < 6; col++) {
                    if (col == 0) {
                        count = 0;
                    }

                    if (currentIndex < Model.Count) {
                        var item = Model[currentIndex];
                        await Html.RenderPartialAsync("_SearchItem", item);
                        currentIndex++;
                    } else {
                        <div class="container col-search"></div>
                    }

                    ++count;
                }

                @if ((currentIndex + 1)! > Model.Count) {
                    if (count != 6) {
                        for (int i = 0; i < (6 - count); ++i) {
                            <div class="container col-search"></div>
                        }
                    }
                }
            </div>
        }
    }
</div>

Website/MtG_UCC/MtG_UCC/Views/Shared/_SearchPartial.cshtml
@using MtG_UCC.Models.Scryfall_Search

@model TrimmedSearch

<form asp-controller="@ViewContext.RouteData.Values["controller"]" asp-action="@ViewContext.RouteData.Values["action"]" method="post">
    <div class="container justify-content-center border border-2 border-dark rounded-2 col-7 CardBack">
        <div class="container my-2 border border-2 border-dark rounded-2 FormBack">
            <div class="row justify-content-center my-2">
                <div class="col-auto">
                    <div class="form-group row">
                        <div class="col-auto">
                            @Html.LabelFor(m => m.CardName, new { @class = "col-form-label" })
                        </div>
                        <div class="col-auto">
                            @Html.TextBoxFor(m => m.CardName, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="form-group row">
                        <div class="col-auto">
                            @Html.LabelFor(m => m.Set, new { @class = "col-form-label" })
                        </div>
                        <div class="col-auto">
                            @Html.TextBoxFor(m => m.Set, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mb-2 border border-2 border-dark rounded-2 FormBack">
            <div class="row justify-content-center my-2">
                <div class="col-auto mx-4 mana-checkbox" onclick="toggleManaCheckbox(this)">
                    <span class="mana-icon check-swamp undecided"></span>
                    @Html.DropDownListFor(m => m.Colors.Black, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                </div>
                <div class="col-auto mx-4 mana-checkbox" onclick="toggleManaCheckbox(this)">
                    <span class="mana-icon check-forest undecided"></span>
                    @Html.DropDownListFor(m => m.Colors.Green, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                </div>
                <div class="col-auto mx-4 mana-checkbox" onclick="toggleManaCheckbox(this)">
                    <span class="mana-icon check-mountain undecided"></span>
                    @Html.DropDownListFor(m => m.Colors.Red, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                </div>
                <div class="col-auto mx-4 mana-checkbox" onclick="toggleManaCheckbox(this)">
                    <span class="mana-icon check-island undecided"></span>
                    @Html.DropDownListFor(m => m.Colors.Blue, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                </div>
                <div class="col-auto mx-4 mana-checkbox" onclick="toggleManaCheckbox(this)">
                    <span class="mana-icon check-plain undecided"></span>
                    @Html.DropDownListFor(m => m.Colors.White, Html.GetEnumSelectList(typeof(ColorOption)), new { @class = "d-none form-control" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="d-flex flex-row justify-content-center mb-2">
                <button class="btn btn-block btn-Forest_BG w-50 px-5" type="submit">Search</button>
            </div>
        </div>
    </div>
</form>

Website/MtG_UCC/MtG_UCC/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using MtG_UCC.Models.Database;
@using MtG_UCC.Models.Microsoft_Identity;
@model UsersWithRoles

@{
    List<IdentityRole> roles = (List<IdentityRole>)ViewData["RolesList"];
    var uuid = Guid.NewGuid();

    var temp = "user_" + uuid;
}

<tr>
    <td>@Model.UserId</td>
    <td>@Model.UserName</td>
    <td>
        @Html.TextBoxFor(m => m.RoleName, new { @type="hidden" })
        @Html.DropDownListFor(m => m.RoleId, new SelectList(roles, "Id", "Name"), new { @form=$"{temp}" })
    </td>
    <td>
        <form id="@("user_" + uuid)" asp-controller="Admin" asp-action="EditRole" method="post">
            <input type="hidden" name="UserId" value="@Model.UserId" />
            <button type="submit" class="btn btn-primary save-button">Save</button>
        </form>
    </td>
</tr>